# Generated by Django 4.1.2 on 2022-10-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_slug',
            field=models.CharField(default='one', max_length=50),
            preserve_default=False,
        ),
    ]
