# Generated by Django 4.1.2 on 2022-10-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0002_topic_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
