# Generated by Django 4.1.2 on 2022-10-13 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0003_alter_topic_topic_name_alter_topic_topic_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_slug',
            new_name='slug',
        ),
    ]
