# Generated by Django 4.1.2 on 2022-10-13 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0004_rename_topic_slug_topic_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_text',
            new_name='text',
        ),
    ]
