# Generated by Django 4.1.2 on 2022-10-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0005_rename_topic_name_topic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, null=True)),
                ('text', models.CharField(max_length=400, null=True)),
                ('value', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
