# Generated by Django 4.1.2 on 2022-10-13 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0006_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
