# Generated by Django 4.1.2 on 2022-10-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0008_new_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(
                choices=[('Macro', 'Macro'), ('Covid-19', 'Covid-19'), ('UARU', 'Ukraine Russia Conflict')],
                max_length=100, null=True),
        ),
    ]
