# Generated by Django 4.1.2 on 2022-10-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0010_remove_topic_slug_remove_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Macro'), (2, 'Covid-19'), (3, 'Ukraine Russia Conflict')], null=True),
        ),
    ]
