# Generated by Django 4.1.2 on 2022-10-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0011_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
